version: '3'

services:
  docker-chautari-mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chautari-dev
      - MYSQL_PASSWORD=root
  chautari-webapp:
    build: .
    depends_on:
      - docker-chautari-mysql
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test
      - DATABASE_PORT=3306